Course.delete_all
acct430 = Course.create("dept" => "ACCT", "course_no" => "430", "course_name" => "Accounting For Decision Making")
acct431 = Course.create("dept" => "ACCT", "course_no" => "431", "course_name" => "Managerial Accounting")
acct434 = Course.create("dept" => "ACCT", "course_no" => "434", "course_name" => "Turbo Accounting")
acct438 = Course.create("dept" => "ACCT", "course_no" => "438", "course_name" => "Accounting for Decision Making")
acct440 = Course.create("dept" => "ACCT", "course_no" => "440", "course_name" => "MMM Accounting for Decision Making")
acct442 = Course.create("dept" => "ACCT", "course_no" => "442", "course_name" => "Strategic Profitability Management")
acct444 = Course.create("dept" => "ACCT", "course_no" => "444", "course_name" => "Financial Planning For Mergers and Acquisitions")
acct451 = Course.create("dept" => "ACCT", "course_no" => "451", "course_name" => "Financial Reporting and Analysis")
acct452 = Course.create("dept" => "ACCT", "course_no" => "452", "course_name" => "Financial Reporting and Analysis II")
acct454 = Course.create("dept" => "ACCT", "course_no" => "454", "course_name" => "Management Lab")
acct459 = Course.create("dept" => "ACCT", "course_no" => "459", "course_name" => "Sustainability Reporting and Analysis")
acct499 = Course.create("dept" => "ACCT", "course_no" => "499", "course_name" => "Independent Study")
acct920 = Course.create("dept" => "ACCT", "course_no" => "920", "course_name" => "Financial Analysis for Strategic Marketing")
blaw435 = Course.create("dept" => "BLAW", "course_no" => "435", "course_name" => "Business Law I")
blaw437 = Course.create("dept" => "BLAW", "course_no" => "437", "course_name" => "Issues In Antitrust")
blaw499 = Course.create("dept" => "BLAW", "course_no" => "499", "course_name" => "Independent Study")
blaw911 = Course.create("dept" => "BLAW", "course_no" => "911", "course_name" => "Business Law for Entrepreneurs")
blaw911 = Course.create("dept" => "BLAW", "course_no" => "911", "course_name" => "Business Law for Entrepreneurs")
blaw917 = Course.create("dept" => "BLAW", "course_no" => "917", "course_name" => "Business Law and Contracts")
blaw925 = Course.create("dept" => "BLAW", "course_no" => "925", "course_name" => "Mergers, Acquisitions and Industry Consolidation: A Case Study")
blaw950 = Course.create("dept" => "BLAW", "course_no" => "950", "course_name" => "Corporate Compliance")
decs430 = Course.create("dept" => "DECS", "course_no" => "430", "course_name" => "Business Analytics I")
decs430 = Course.create("dept" => "DECS", "course_no" => "430", "course_name" => "Business Analytics I")
decs431 = Course.create("dept" => "DECS", "course_no" => "431", "course_name" => "Business Analytics II")
decs438 = Course.create("dept" => "DECS", "course_no" => "438", "course_name" => "Managerial Decision Analysis")
decs439 = Course.create("dept" => "DECS", "course_no" => "439", "course_name" => "Statistical Decision Analysis")
decs440 = Course.create("dept" => "DECS", "course_no" => "440", "course_name" => "MMM Business Analytics")
decs450 = Course.create("dept" => "DECS", "course_no" => "450", "course_name" => "Decision Making & Modeling")
decs452 = Course.create("dept" => "DECS", "course_no" => "452", "course_name" => "Game Theory and Strategic Decisions (formerly Strategic Decision Making)")
decs499 = Course.create("dept" => "DECS", "course_no" => "499", "course_name" => "Independent Study")
decs499 = Course.create("dept" => "DECS", "course_no" => "499", "course_name" => "Independent Study")
decs915 = Course.create("dept" => "DECS", "course_no" => "915", "course_name" => "Analytical Consulting Lab (ACL)")
decs915 = Course.create("dept" => "DECS", "course_no" => "915", "course_name" => "Analytics Consulting Lab (ACL)")
decs915 = Course.create("dept" => "DECS", "course_no" => "915", "course_name" => "Analytics Consulting Lab (ACL)")
decs920 = Course.create("dept" => "DECS", "course_no" => "920", "course_name" => "Risk Lab")
finc430 = Course.create("dept" => "FINC", "course_no" => "430", "course_name" => "Finance I")
finc440 = Course.create("dept" => "FINC", "course_no" => "440", "course_name" => "Finance I/II")
finc441 = Course.create("dept" => "FINC", "course_no" => "441", "course_name" => "Finance II")
finc442 = Course.create("dept" => "FINC", "course_no" => "442", "course_name" => "Financial Decisions")
finc444 = Course.create("dept" => "FINC", "course_no" => "444", "course_name" => "Value Investing (formerly FINC-925 Advanced Topics in Finance)")
finc445 = Course.create("dept" => "FINC", "course_no" => "445", "course_name" => "Entrepreneurial Finance and Venture Capital")
finc446 = Course.create("dept" => "FINC", "course_no" => "446", "course_name" => "Entrepreneurial Finance")
finc447 = Course.create("dept" => "FINC", "course_no" => "447", "course_name" => "Financial Strategy and Tax Planning")
finc448 = Course.create("dept" => "FINC", "course_no" => "448", "course_name" => "M&As, LBOs and Corporate Restructuring")
finc451 = Course.create("dept" => "FINC", "course_no" => "451", "course_name" => "Money Markets and the Fed")
finc454 = Course.create("dept" => "FINC", "course_no" => "454", "course_name" => "Real Estate Finance and Investments")
finc455 = Course.create("dept" => "FINC", "course_no" => "455", "course_name" => "Real Estate Finance and Investments II")
finc460 = Course.create("dept" => "FINC", "course_no" => "460", "course_name" => "Investments")
finc461 = Course.create("dept" => "FINC", "course_no" => "461", "course_name" => "Investment Banking")
finc462 = Course.create("dept" => "FINC", "course_no" => "462", "course_name" => "Portfolio Management")
finc463 = Course.create("dept" => "FINC", "course_no" => "463", "course_name" => "Securities Analysis")
finc464 = Course.create("dept" => "FINC", "course_no" => "464", "course_name" => "Fixed Income Securities")
finc465 = Course.create("dept" => "FINC", "course_no" => "465", "course_name" => "Derivatives Markets I")
finc467 = Course.create("dept" => "FINC", "course_no" => "467", "course_name" => "Derivatives Markets II")
finc470 = Course.create("dept" => "FINC", "course_no" => "470", "course_name" => "International Finance")
finc471 = Course.create("dept" => "FINC", "course_no" => "471", "course_name" => "Case Studies in Venture Investment")
finc484 = Course.create("dept" => "FINC", "course_no" => "484", "course_name" => "Thought Leadership Seminar: Contemporary Issues in Finance")
finc499 = Course.create("dept" => "FINC", "course_no" => "499", "course_name" => "Independent Study")
finc499 = Course.create("dept" => "FINC", "course_no" => "499", "course_name" => "Independent Study")
finc499 = Course.create("dept" => "FINC", "course_no" => "499", "course_name" => "Independent Study")
finc915 = Course.create("dept" => "FINC", "course_no" => "915", "course_name" => "Venture Lab (V-Lab)")
finc916 = Course.create("dept" => "FINC", "course_no" => "916", "course_name" => "VC Experience")
finc918 = Course.create("dept" => "FINC", "course_no" => "918", "course_name" => "Major Project and Project Finance in Emerging Markets")
finc931 = Course.create("dept" => "FINC", "course_no" => "931", "course_name" => "Wall Street, Hedge Funds and Private Equity")
finc933 = Course.create("dept" => "FINC", "course_no" => "933", "course_name" => "Asset Management Practicum I")
finc934 = Course.create("dept" => "FINC", "course_no" => "934", "course_name" => "Asset Management Practicum II")
finc935 = Course.create("dept" => "FINC", "course_no" => "935", "course_name" => "Asset Management Practicum III")
finc936 = Course.create("dept" => "FINC", "course_no" => "936", "course_name" => "Asset Management Practicum IV")
finc937 = Course.create("dept" => "FINC", "course_no" => "937", "course_name" => "Microfinance & the Role of Financial Institutions in Development")
finc937 = Course.create("dept" => "FINC", "course_no" => "937", "course_name" => "Microfinance & the Role of Financial Institutions in Development")
finc939 = Course.create("dept" => "FINC", "course_no" => "939", "course_name" => "Buyout Lab (B-Lab)")
finc940 = Course.create("dept" => "FINC", "course_no" => "940", "course_name" => "Financial Modeling for Leveraged Buyout Transactions")
finc941 = Course.create("dept" => "FINC", "course_no" => "941", "course_name" => "Macroeconomic Policy and Global Capital Markets")
finc944 = Course.create("dept" => "FINC", "course_no" => "944", "course_name" => "Investment Banking Recruiting Prep")
finc945 = Course.create("dept" => "FINC", "course_no" => "945", "course_name" => "Global Entrepreneurial Finance")
finc946 = Course.create("dept" => "FINC", "course_no" => "946", "course_name" => "Impact Investing (Formerly SEEK-921-0)")
finc970 = Course.create("dept" => "FINC", "course_no" => "970", "course_name" => "Empirical Methods in Finance")
hema440 = Course.create("dept" => "HEMA", "course_no" => "440", "course_name" => "Healthcare Systems (formerly HIMT-440-0)")
hema441 = Course.create("dept" => "HEMA", "course_no" => "441", "course_name" => "Health Policy (formerly HIMT-441-0)")
hema451 = Course.create("dept" => "HEMA", "course_no" => "451", "course_name" => "Legal Issues in Health Care Delivery (formerly HIMT-451)")
hema452 = Course.create("dept" => "HEMA", "course_no" => "452", "course_name" => "Advanced Strategic Management in Healthcare (formerly HIMT-452-B)")
hema453 = Course.create("dept" => "HEMA", "course_no" => "453", "course_name" => "Managerial Challenges in the Pharmaceutical, Biotech, and Medical Device Industries (formerly HIMT-453-0)")
hema499 = Course.create("dept" => "HEMA", "course_no" => "499", "course_name" => "Independent Study")
hema499 = Course.create("dept" => "HEMA", "course_no" => "499", "course_name" => "Independent Study")
hema499 = Course.create("dept" => "HEMA", "course_no" => "499", "course_name" => "Independent Study")
hema512 = Course.create("dept" => "HEMA", "course_no" => "512", "course_name" => "Health Services Management Field Study/Project Management (formerly HIMT-512-0)")
hema910 = Course.create("dept" => "HEMA", "course_no" => "910", "course_name" => "Science Boot Camp (Formerly BIOT-910-A) (non-credit)")
hema911 = Course.create("dept" => "HEMA", "course_no" => "911", "course_name" => "Healthcare Bootcamp (non credit)")
hema911 = Course.create("dept" => "HEMA", "course_no" => "911", "course_name" => "Healthcare Bootcamp (non-credit)")
hema913 = Course.create("dept" => "HEMA", "course_no" => "913", "course_name" => "Biotech Business Practicum (formerly BIOT-913-0)")
hema914 = Course.create("dept" => "HEMA", "course_no" => "914", "course_name" => "Biomedical Marketing (formerly BIOT-914-0)")
hema915 = Course.create("dept" => "HEMA", "course_no" => "915", "course_name" => "NUvention: Medical Innovation I (formerly BIOT-915-0)")
hema916 = Course.create("dept" => "HEMA", "course_no" => "916", "course_name" => "NUvention: Medical Innovation II (formerly BIOT-916-0)")
hema920 = Course.create("dept" => "HEMA", "course_no" => "920", "course_name" => "Hospital - Physician- Insurer Relationships and the Response to Healthcare Reform")
hema920 = Course.create("dept" => "HEMA", "course_no" => "920", "course_name" => "Healthcare Markets")
hema921 = Course.create("dept" => "HEMA", "course_no" => "921", "course_name" => "Health Information Technology")
hema922 = Course.create("dept" => "HEMA", "course_no" => "922", "course_name" => "Health Care Quality")
hema923 = Course.create("dept" => "HEMA", "course_no" => "923", "course_name" => "Topics in Health Policy: The Affordable Care Act")
hema924 = Course.create("dept" => "HEMA", "course_no" => "924", "course_name" => "Population Health: Healthcare transformation as a necessary result of economic, policy and demographic forces")
hema925 = Course.create("dept" => "HEMA", "course_no" => "925", "course_name" => "Healthcare Markets (Formerly HEMA-920-B)")
hema926 = Course.create("dept" => "HEMA", "course_no" => "926", "course_name" => "Patient-Centric Business Models, Solution and Strategies")
hema930 = Course.create("dept" => "HEMA", "course_no" => "930", "course_name" => "Health Plan Design and Financing")
intl473 = Course.create("dept" => "INTL", "course_no" => "473", "course_name" => "Global Initiatives in Management (GIM)")
intl490 = Course.create("dept" => "INTL", "course_no" => "490", "course_name" => "Foreign Study")
intl499 = Course.create("dept" => "INTL", "course_no" => "499", "course_name" => "Independent Study")
intl499 = Course.create("dept" => "INTL", "course_no" => "499", "course_name" => "Independent Study")
intl915 = Course.create("dept" => "INTL", "course_no" => "915", "course_name" => "Global Lab (G-Lab)")
intl916 = Course.create("dept" => "INTL", "course_no" => "916", "course_name" => "International Business Strategy Lab (IBS-Lab)")
intl920 = Course.create("dept" => "INTL", "course_no" => "920", "course_name" => "The Changing Nature of Business and Economy in China")
intl925 = Course.create("dept" => "INTL", "course_no" => "925", "course_name" => "International Trade and Commerce")
intl925 = Course.create("dept" => "INTL", "course_no" => "925", "course_name" => "International Trade and Commerce: THe Global Wine Industry")
kiei452 = Course.create("dept" => "KIEI", "course_no" => "452", "course_name" => "Social Entrepreneurship")
kiei462 = Course.create("dept" => "KIEI", "course_no" => "462", "course_name" => "New Venture Discovery")
kiei463 = Course.create("dept" => "KIEI", "course_no" => "463", "course_name" => "Successful Entrepreneurship")
kiei499 = Course.create("dept" => "KIEI", "course_no" => "499", "course_name" => "Independent Study")
kiei499 = Course.create("dept" => "KIEI", "course_no" => "499", "course_name" => "Independent Study")
kiei499 = Course.create("dept" => "KIEI", "course_no" => "499", "course_name" => "Independent Study")
kiei901 = Course.create("dept" => "KIEI", "course_no" => "901", "course_name" => "Managing Enterprise Risk")
kiei902 = Course.create("dept" => "KIEI", "course_no" => "902", "course_name" => "Entrepreneurial Selling")
kiei902 = Course.create("dept" => "KIEI", "course_no" => "902", "course_name" => "Entrepreneurial Selling")
kiei903 = Course.create("dept" => "KIEI", "course_no" => "903", "course_name" => "Corporate Innovation and New Ventures")
kiei903 = Course.create("dept" => "KIEI", "course_no" => "903", "course_name" => "Corporate Innovation & New Ventures (INSEAD)")
kiei911 = Course.create("dept" => "KIEI", "course_no" => "911", "course_name" => "Medical Product Early Stage Commercialization")
kiei920 = Course.create("dept" => "KIEI", "course_no" => "920", "course_name" => "KIN Challenge")
kiei925 = Course.create("dept" => "KIEI", "course_no" => "925", "course_name" => "Startup Programming and Management")
kiei926 = Course.create("dept" => "KIEI", "course_no" => "926", "course_name" => "Venture Capital and Private Equity: The Human Element")
kiei930 = Course.create("dept" => "KIEI", "course_no" => "930", "course_name" => "NUvention -- Innovate for Impact I")
kiei931 = Course.create("dept" => "KIEI", "course_no" => "931", "course_name" => "NUVention -- Innovate for Impact II")
kiei932 = Course.create("dept" => "KIEI", "course_no" => "932", "course_name" => "Product Management for Technology Companies")
kiei935 = Course.create("dept" => "KIEI", "course_no" => "935", "course_name" => "Intellectual Property for Entrepreneurs")
kiei940 = Course.create("dept" => "KIEI", "course_no" => "940", "course_name" => "Innovation Lab I")
kiei941 = Course.create("dept" => "KIEI", "course_no" => "941", "course_name" => "Enterprise Models for Social Change")
kiei941 = Course.create("dept" => "KIEI", "course_no" => "941", "course_name" => "Enterprise Innovation for Social Change")
kiei942 = Course.create("dept" => "KIEI", "course_no" => "942", "course_name" => "Innovation Lab II")
kiei943 = Course.create("dept" => "KIEI", "course_no" => "943", "course_name" => "Social Intrapreneurship")
kiei950 = Course.create("dept" => "KIEI", "course_no" => "950", "course_name" => "NUvention: Web I")
kiei951 = Course.create("dept" => "KIEI", "course_no" => "951", "course_name" => "NUvention: Energy")
kiei952 = Course.create("dept" => "KIEI", "course_no" => "952", "course_name" => "NUvention: Web II")
kiei965 = Course.create("dept" => "KIEI", "course_no" => "965", "course_name" => "Global Governance of Private Companies")
kiei967 = Course.create("dept" => "KIEI", "course_no" => "967", "course_name" => "The Entrepreneurial Experience")
kppi440 = Course.create("dept" => "KPPI", "course_no" => "440", "course_name" => "Leadership and Crisis Management")
kppi441 = Course.create("dept" => "KPPI", "course_no" => "441", "course_name" => "Strategic Management in Non-Market Environments")
kppi442 = Course.create("dept" => "KPPI", "course_no" => "442", "course_name" => "International Healthcare Systems")
kppi450 = Course.create("dept" => "KPPI", "course_no" => "450", "course_name" => "Leading the Mission Driven Enterprise")
kppi453 = Course.create("dept" => "KPPI", "course_no" => "453", "course_name" => "Board Governance of Non-Profit Organizations")
kppi454 = Course.create("dept" => "KPPI", "course_no" => "454", "course_name" => "The Education Industry")
kppi455 = Course.create("dept" => "KPPI", "course_no" => "455", "course_name" => "Board Governance of Non-Profit Organizations (Board Fellows)")
kppi455 = Course.create("dept" => "KPPI", "course_no" => "455", "course_name" => "Board Governance of Non-Profit Organizations (Non-Board Fellows)")
kppi460 = Course.create("dept" => "KPPI", "course_no" => "460", "course_name" => "Values Based Leadership")
kppi470 = Course.create("dept" => "KPPI", "course_no" => "470", "course_name" => "Public Economics for Business Leaders: Federal Policy")
kppi471 = Course.create("dept" => "KPPI", "course_no" => "471", "course_name" => "Advanced Board Governance")
kppi471 = Course.create("dept" => "KPPI", "course_no" => "471", "course_name" => "Advanced Board Governance (Half-Credit)")
kppi471 = Course.create("dept" => "KPPI", "course_no" => "471", "course_name" => "Advanced Board Governance (non-credit)")
kppi480 = Course.create("dept" => "KPPI", "course_no" => "480", "course_name" => "Public Economics for Business Leaders: State and Local Policy")
kppi484 = Course.create("dept" => "KPPI", "course_no" => "484", "course_name" => "Thought Leadership Seminar")
kppi484 = Course.create("dept" => "KPPI", "course_no" => "484", "course_name" => "Thought Leadership Seminar")
kppi499 = Course.create("dept" => "KPPI", "course_no" => "499", "course_name" => "Independent Study")
kppi915 = Course.create("dept" => "KPPI", "course_no" => "915", "course_name" => "Business Opportunities in Energy Markets")
kppi917 = Course.create("dept" => "KPPI", "course_no" => "917", "course_name" => "Corporate Social Innovation")
kppi917 = Course.create("dept" => "KPPI", "course_no" => "917", "course_name" => "Corporate Social Innovation")
kppi918 = Course.create("dept" => "KPPI", "course_no" => "918", "course_name" => "Education Consulting Lab ")
kppi918 = Course.create("dept" => "KPPI", "course_no" => "918", "course_name" => "Education Consulting Lab (Half Credit)")
kppi933 = Course.create("dept" => "KPPI", "course_no" => "933", "course_name" => "Health and Human Rights")
kppi935 = Course.create("dept" => "KPPI", "course_no" => "935", "course_name" => "Environmental Management and Sustainability")
kppi973 = Course.create("dept" => "KPPI", "course_no" => "973", "course_name" => "Medical Technologies in Developing Countries II")
kppi973 = Course.create("dept" => "KPPI", "course_no" => "973", "course_name" => "Medical Technologies in Developing Countries I")
mecn430 = Course.create("dept" => "MECN", "course_no" => "430", "course_name" => "Microeconomic Analysis")
mecn441 = Course.create("dept" => "MECN", "course_no" => "441", "course_name" => "Competitive Strategy and Industrial Structure")
mecn446 = Course.create("dept" => "MECN", "course_no" => "446", "course_name" => "Pricing Strategies")
mecn450 = Course.create("dept" => "MECN", "course_no" => "450", "course_name" => "Macroeconomics")
mecn499 = Course.create("dept" => "MECN", "course_no" => "499", "course_name" => "Independent Study")
mecn499 = Course.create("dept" => "MECN", "course_no" => "499", "course_name" => "Independent Study")
medm432 = Course.create("dept" => "MEDM", "course_no" => "432", "course_name" => "Understanding Media and Content")
medm499 = Course.create("dept" => "MEDM", "course_no" => "499", "course_name" => "Independent Study")
medm499 = Course.create("dept" => "MEDM", "course_no" => "499", "course_name" => "Independent Study")
medm499 = Course.create("dept" => "MEDM", "course_no" => "499", "course_name" => "Independent Study")
medm911 = Course.create("dept" => "MEDM", "course_no" => "911", "course_name" => "Media Strategy and Implementation")
medm914 = Course.create("dept" => "MEDM", "course_no" => "914", "course_name" => "Media Management Strategy Project")
medm915 = Course.create("dept" => "MEDM", "course_no" => "915", "course_name" => "Managing Digital Media")
medm915 = Course.create("dept" => "MEDM", "course_no" => "915", "course_name" => "Managing Digital Media")
medm916 = Course.create("dept" => "MEDM", "course_no" => "916", "course_name" => "Changing Business Models in the Media Industry")
medm926 = Course.create("dept" => "MEDM", "course_no" => "926", "course_name" => "Leading and Organizing Media Companies")
mgmt431 = Course.create("dept" => "MGMT", "course_no" => "431", "course_name" => "Business Strategy")
mgmt440 = Course.create("dept" => "MGMT", "course_no" => "440", "course_name" => "Personnel Strategy")
mgmt441 = Course.create("dept" => "MGMT", "course_no" => "441", "course_name" => "Intellectual Capital Management")
mgmt444 = Course.create("dept" => "MGMT", "course_no" => "444", "course_name" => "Health Economics")
mgmt452 = Course.create("dept" => "MGMT", "course_no" => "452", "course_name" => "Strategy & Organization")
mgmt460 = Course.create("dept" => "MGMT", "course_no" => "460", "course_name" => "International Business Strategy")
mgmt463 = Course.create("dept" => "MGMT", "course_no" => "463", "course_name" => "Technology and Innovation Strategy")
mgmt466 = Course.create("dept" => "MGMT", "course_no" => "466", "course_name" => "International Business Strategy in Non-Market Environments")
mgmt469 = Course.create("dept" => "MGMT", "course_no" => "469", "course_name" => "Empirical Methods in Strategy")
mgmt491 = Course.create("dept" => "MGMT", "course_no" => "491", "course_name" => "Visiting Away")
mgmt499 = Course.create("dept" => "MGMT", "course_no" => "499", "course_name" => "Independent Study")
mgmt499 = Course.create("dept" => "MGMT", "course_no" => "499", "course_name" => "Independent Study")
mgmt499 = Course.create("dept" => "MGMT", "course_no" => "499", "course_name" => "Independent Study")
mgmt512 = Course.create("dept" => "MGMT", "course_no" => "512", "course_name" => "Intl Practicum/Cross-Cultural Management Practice")
mgmt911 = Course.create("dept" => "MGMT", "course_no" => "911", "course_name" => "Strategic Business Profit")
mgmt913 = Course.create("dept" => "MGMT", "course_no" => "913", "course_name" => "Corporate Governance")
mgmt927 = Course.create("dept" => "MGMT", "course_no" => "927", "course_name" => "Family Enterprises: Issues & Solutions")
mgmt930 = Course.create("dept" => "MGMT", "course_no" => "930", "course_name" => "Globality")
mgmt931 = Course.create("dept" => "MGMT", "course_no" => "931", "course_name" => "Strategic Franchising")
mgmt931 = Course.create("dept" => "MGMT", "course_no" => "931", "course_name" => "Strategic Franchising")
mgmt934 = Course.create("dept" => "MGMT", "course_no" => "934", "course_name" => "Managing Turnarounds")
mgmt941 = Course.create("dept" => "MGMT", "course_no" => "941", "course_name" => "Issues in Air Transportation")
mgmt942 = Course.create("dept" => "MGMT", "course_no" => "942", "course_name" => "Career Lab")
mgmt943 = Course.create("dept" => "MGMT", "course_no" => "943", "course_name" => "Advanced Business Strategy")
mgmt944 = Course.create("dept" => "MGMT", "course_no" => "944", "course_name" => "Advanced Turnarounds")
mgmt945 = Course.create("dept" => "MGMT", "course_no" => "945", "course_name" => "Healthcare Strategy")
mgmt946 = Course.create("dept" => "MGMT", "course_no" => "946", "course_name" => "Strategy, Competition, and Policy in Healthcare Markets")
mgmt950 = Course.create("dept" => "MGMT", "course_no" => "950", "course_name" => "Competitive Strategy in Financial Markets")
mgmt950 = Course.create("dept" => "MGMT", "course_no" => "950", "course_name" => "Competitive Strategy in Financial Markets")
mgmt955 = Course.create("dept" => "MGMT", "course_no" => "955", "course_name" => "Strategies for Growth")
mgmt955 = Course.create("dept" => "MGMT", "course_no" => "955", "course_name" => "Strategies for Growth")
mgmt960 = Course.create("dept" => "MGMT", "course_no" => "960", "course_name" => "Strategy to Execution - A Capabilities Approach")
mgmt989 = Course.create("dept" => "MGMT", "course_no" => "989", "course_name" => "Opportunity Mining in The Real World")
mktg430 = Course.create("dept" => "MKTG", "course_no" => "430", "course_name" => "Marketing Management")
mktg440 = Course.create("dept" => "MKTG", "course_no" => "440", "course_name" => "MMM Marketing Management")
mktg450 = Course.create("dept" => "MKTG", "course_no" => "450", "course_name" => "Research Methods In Marketing")
mktg451 = Course.create("dept" => "MKTG", "course_no" => "451", "course_name" => "Marketing Channel Strategies")
mktg452 = Course.create("dept" => "MKTG", "course_no" => "452", "course_name" => "Consumer Insight Tools")
mktg453 = Course.create("dept" => "MKTG", "course_no" => "453", "course_name" => "Business Marketing")
mktg454 = Course.create("dept" => "MKTG", "course_no" => "454", "course_name" => "Advertising Strategy")
mktg455 = Course.create("dept" => "MKTG", "course_no" => "455", "course_name" => "Media and Integrated Marketing (formerly MEDM-431)")
mktg458 = Course.create("dept" => "MKTG", "course_no" => "458", "course_name" => "Consumer Insight for Brand Strategy")
mktg459 = Course.create("dept" => "MKTG", "course_no" => "459", "course_name" => "Services Marketing and Management")
mktg462 = Course.create("dept" => "MKTG", "course_no" => "462", "course_name" => "Retail Analytics, Pricing and Promotion")
mktg463 = Course.create("dept" => "MKTG", "course_no" => "463", "course_name" => "Sales Force Management")
mktg464 = Course.create("dept" => "MKTG", "course_no" => "464", "course_name" => "The Management of Product Development")
mktg464 = Course.create("dept" => "MKTG", "course_no" => "464", "course_name" => "Product Design and Marketing")
mktg465 = Course.create("dept" => "MKTG", "course_no" => "465", "course_name" => "Marketing-Led Innovation")
mktg466 = Course.create("dept" => "MKTG", "course_no" => "466", "course_name" => "Marketing Strategy")
mktg467 = Course.create("dept" => "MKTG", "course_no" => "467", "course_name" => "Global Marketing")
mktg468 = Course.create("dept" => "MKTG", "course_no" => "468", "course_name" => "Technology Marketing")
mktg499 = Course.create("dept" => "MKTG", "course_no" => "499", "course_name" => "Independent Study")
mktg499 = Course.create("dept" => "MKTG", "course_no" => "499", "course_name" => "Independent Study")
mktg499 = Course.create("dept" => "MKTG", "course_no" => "499", "course_name" => "Independent Study")
mktg913 = Course.create("dept" => "MKTG", "course_no" => "913", "course_name" => "Internet Marketing")
mktg922 = Course.create("dept" => "MKTG", "course_no" => "922", "course_name" => "Advanced Topics in Marketing")
mktg930 = Course.create("dept" => "MKTG", "course_no" => "930", "course_name" => "Social Impact Marketing")
mktg940 = Course.create("dept" => "MKTG", "course_no" => "940", "course_name" => "C Suite and Boardroom Dynamics")
mktg945 = Course.create("dept" => "MKTG", "course_no" => "945", "course_name" => "Design Lab")
mktg950 = Course.create("dept" => "MKTG", "course_no" => "950", "course_name" => "Marketing Project Laboratory Course: Generating Profitable Growth")
mktg951 = Course.create("dept" => "MKTG", "course_no" => "951", "course_name" => "Sports Marketing and Management")
mktg952 = Course.create("dept" => "MKTG", "course_no" => "952", "course_name" => "Strategic Data-Driven Marketing")
mktg953 = Course.create("dept" => "MKTG", "course_no" => "953", "course_name" => "Customer Analytics")
mktg955 = Course.create("dept" => "MKTG", "course_no" => "955", "course_name" => "Digital Marketing Analytics")
mktg957 = Course.create("dept" => "MKTG", "course_no" => "957", "course_name" => "Digital Marketing and Commerce")
mktg958 = Course.create("dept" => "MKTG", "course_no" => "958", "course_name" => "At the Forefront: Social Media and Engagement")
mktg958 = Course.create("dept" => "MKTG", "course_no" => "958", "course_name" => "At the Forefront: Social Media and Engagement")
mktg959 = Course.create("dept" => "MKTG", "course_no" => "959", "course_name" => "Marketing in Developing Economies")
mktg961 = Course.create("dept" => "MKTG", "course_no" => "961", "course_name" => "Entrepreneurial Tools for Digital Marketing")
mktg961 = Course.create("dept" => "MKTG", "course_no" => "961", "course_name" => "Entrepreneurial Tools for Digital Marketing")
mktg962 = Course.create("dept" => "MKTG", "course_no" => "962", "course_name" => "Entrepreneurial Selling: Business to Business")
mktg962 = Course.create("dept" => "MKTG", "course_no" => "962", "course_name" => "Entrepreneurial Selling: Business to Business")
mors430 = Course.create("dept" => "MORS", "course_no" => "430", "course_name" => "Leadership in Organizations")
mors441 = Course.create("dept" => "MORS", "course_no" => "441", "course_name" => "Managing People for Competitive Advantage")
mors441 = Course.create("dept" => "MORS", "course_no" => "441", "course_name" => "Managing People for Competitive Advantage")
mors441 = Course.create("dept" => "MORS", "course_no" => "441", "course_name" => "Managing People for Competitive Advantage (INSEAD)")
mors449 = Course.create("dept" => "MORS", "course_no" => "449", "course_name" => "Writing in Organizations")
mors449 = Course.create("dept" => "MORS", "course_no" => "449", "course_name" => "Writing in Organizations")
mors450 = Course.create("dept" => "MORS", "course_no" => "450", "course_name" => "Management Communications")
mors451 = Course.create("dept" => "MORS", "course_no" => "451", "course_name" => "Designing Organizational Systems")
mors452 = Course.create("dept" => "MORS", "course_no" => "452", "course_name" => "Leading the Strategic Change Process")
mors452 = Course.create("dept" => "MORS", "course_no" => "452", "course_name" => "Simulating Strategic Change")
mors452 = Course.create("dept" => "MORS", "course_no" => "452", "course_name" => "Simulating Strategic Change")
mors453 = Course.create("dept" => "MORS", "course_no" => "453", "course_name" => "Power In Organizations: Sources, Strategies and Skills")
mors454 = Course.create("dept" => "MORS", "course_no" => "454", "course_name" => "Creating and Managing Strategic Alliances")
mors454 = Course.create("dept" => "MORS", "course_no" => "454", "course_name" => "Creating and Managing Strategic Alliances")
mors455 = Course.create("dept" => "MORS", "course_no" => "455", "course_name" => "Strategy Implementation")
mors460 = Course.create("dept" => "MORS", "course_no" => "460", "course_name" => "Leading and Managing Teams")
mors462 = Course.create("dept" => "MORS", "course_no" => "462", "course_name" => "Leading and Managing Diverse Organizations")
mors462 = Course.create("dept" => "MORS", "course_no" => "462", "course_name" => "Leading and Managing Diverse Organization")
mors468 = Course.create("dept" => "MORS", "course_no" => "468", "course_name" => "Managerial Leadership (formerly MGMT-468-0)")
mors470 = Course.create("dept" => "MORS", "course_no" => "470", "course_name" => "Negotiations")
mors474 = Course.create("dept" => "MORS", "course_no" => "474", "course_name" => "Cross-Cultural Negotiation")
mors476 = Course.create("dept" => "MORS", "course_no" => "476", "course_name" => "Bargaining (formerly MORS-914-0)")
mors499 = Course.create("dept" => "MORS", "course_no" => "499", "course_name" => "Independent Study")
mors499 = Course.create("dept" => "MORS", "course_no" => "499", "course_name" => "Independent Study")
mors920 = Course.create("dept" => "MORS", "course_no" => "920", "course_name" => "Social Media and Reputation")
mors920 = Course.create("dept" => "MORS", "course_no" => "920", "course_name" => "Social Media and Reputation")
mors924 = Course.create("dept" => "MORS", "course_no" => "924", "course_name" => "Consulting: Frameworks and Practice")
mors925 = Course.create("dept" => "MORS", "course_no" => "925", "course_name" => "Business Design for Environmental Sustainability")
mors926 = Course.create("dept" => "MORS", "course_no" => "926", "course_name" => "Strategies, Structures and Tools for Sustaining Innovation (MORS-926-0)")
mors927 = Course.create("dept" => "MORS", "course_no" => "927", "course_name" => "Practice-based Tools for Emerging Technology Markets")
mors933 = Course.create("dept" => "MORS", "course_no" => "933", "course_name" => "Leaders & Leadership")
mors934 = Course.create("dept" => "MORS", "course_no" => "934", "course_name" => "Managing in Professional Service Firms")
mors935 = Course.create("dept" => "MORS", "course_no" => "935", "course_name" => "Personal Leadership Insights")
mors936 = Course.create("dept" => "MORS", "course_no" => "936", "course_name" => "Leadership Coaching Program")
mors936 = Course.create("dept" => "MORS", "course_no" => "936", "course_name" => "Leadership Coaching Course: A Small Group Experience in Self-Reflection & Peer Coaching (Part-Time)")
mors937 = Course.create("dept" => "MORS", "course_no" => "937", "course_name" => "Leader as Coach (Part Time Version)")
mors937 = Course.create("dept" => "MORS", "course_no" => "937", "course_name" => "Leader as Coach")
mors937 = Course.create("dept" => "MORS", "course_no" => "937", "course_name" => "Leader as Coach: Practicum")
mors941 = Course.create("dept" => "MORS", "course_no" => "941", "course_name" => "Comprehensive Perspectives of Leading a Sports Entity")
mors945 = Course.create("dept" => "MORS", "course_no" => "945", "course_name" => "Social Dynamics and Network Analytics")
mors948 = Course.create("dept" => "MORS", "course_no" => "948", "course_name" => "Origins of Organizing")
mors950 = Course.create("dept" => "MORS", "course_no" => "950", "course_name" => "Frameworks to Insights: Problem Solving in Fast Forward")
mors952 = Course.create("dept" => "MORS", "course_no" => "952", "course_name" => "Entrepreneurship: Building Innovation, Teams, and Cultures")
mors952 = Course.create("dept" => "MORS", "course_no" => "952", "course_name" => "Entrepreneurship: Building Innovation, Teams, and Cultures")
mors960 = Course.create("dept" => "MORS", "course_no" => "960", "course_name" => "Negotiations Fundamentals")
opns430 = Course.create("dept" => "OPNS", "course_no" => "430", "course_name" => "Operations Management")
opns438 = Course.create("dept" => "OPNS", "course_no" => "438", "course_name" => "Operations Management (Turbo)")
opns438 = Course.create("dept" => "OPNS", "course_no" => "438", "course_name" => "Operations Management (Turbo)")
opns440 = Course.create("dept" => "OPNS", "course_no" => "440", "course_name" => "Designing and Managing Business Processes")
opns450 = Course.create("dept" => "OPNS", "course_no" => "450", "course_name" => "Analytical Decision Modeling")
opns454 = Course.create("dept" => "OPNS", "course_no" => "454", "course_name" => "Operations Strategy")
opns455 = Course.create("dept" => "OPNS", "course_no" => "455", "course_name" => "Supply Chain Management")
opns458 = Course.create("dept" => "OPNS", "course_no" => "458", "course_name" => "Enterprise Technology Management (Formerly TECH-442-0)")
opns458 = Course.create("dept" => "OPNS", "course_no" => "458", "course_name" => "Enterprise Technology Management")
opns482 = Course.create("dept" => "OPNS", "course_no" => "482", "course_name" => "Service Operations")
opns499 = Course.create("dept" => "OPNS", "course_no" => "499", "course_name" => "Independent Study")
opns499 = Course.create("dept" => "OPNS", "course_no" => "499", "course_name" => "Independent Study")
opns917 = Course.create("dept" => "OPNS", "course_no" => "917", "course_name" => "Project Management")
opns923 = Course.create("dept" => "OPNS", "course_no" => "923", "course_name" => "Enterprise Risk Management")
opns925 = Course.create("dept" => "OPNS", "course_no" => "925", "course_name" => "The New General Manager")
opns930 = Course.create("dept" => "OPNS", "course_no" => "930", "course_name" => "6 Sigma Basics I")
opns931 = Course.create("dept" => "OPNS", "course_no" => "931", "course_name" => "6 Sigma Basics II")
opns932 = Course.create("dept" => "OPNS", "course_no" => "932", "course_name" => "Implementing Process Improvement")
real443 = Course.create("dept" => "REAL", "course_no" => "443", "course_name" => "Urban Economic Development and Real Estate Market Analysis")
real444 = Course.create("dept" => "REAL", "course_no" => "444", "course_name" => "Real Estate Development")
real447 = Course.create("dept" => "REAL", "course_no" => "447", "course_name" => "Legal Issues In Real Estate")
real499 = Course.create("dept" => "REAL", "course_no" => "499", "course_name" => "Independent Study")
real916 = Course.create("dept" => "REAL", "course_no" => "916", "course_name" => "Real Estate Lab")
real922 = Course.create("dept" => "REAL", "course_no" => "922", "course_name" => "International Real Estate")
real925 = Course.create("dept" => "REAL", "course_no" => "925", "course_name" => "Real Estate Entrepreneurship")


Professor.delete_all
russellwalker = Professor.create("pfirst_name" => "Russell ", "plast_name" => "Walker", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/walker_r.ashx")
jeffcohen = Professor.create("pfirst_name" => "Jeff", "plast_name" => "Cohen", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Cohen_Jeff.ashx")
davidschoanthal = Professor.create("pfirst_name" => "David", "plast_name" => "Schoanthal", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Schonthal_David.ashx")
timcalkins =Professor.create("pfirst_name" => "Tim", "plast_name" => "Calkins", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/calkins_tim.ashx")
navinchopra = Professor.create("pfirst_name" => "Navin", "plast_name" => "Chopra", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Chopra_Navin.ashx")
markfinn = Professor.create("pfirst_name" => "Mark", "plast_name" => "Finn", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/finn_m.ashx")
jenbrown = Professor.create("pfirst_name" => "Jen", "plast_name" => "Brown", "gender" => "F", "photo_url" => "http://www.kellogg.northwestern.edu/faculty/brown_j/htm/brownresearch_files/image002.png")
jamesnaughton = Professor.create("pfirst_name" => "James", "plast_name" => "Naughton", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Naughton_James.ashx")
craigfurfine = Professor.create("pfirst_name" => "Craig", "plast_name" => "Furfine", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/furfine_c.ashx")
chiragsaraiya = Professor.create("pfirst_name" => "Chirag", "plast_name" => "Saraiya", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/saraiya_c.ashx")
phillipbraun = Professor.create("pfirst_name" => "Phillip", "plast_name" => "Braun", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/braun_phillip.ashx")
daviddranov = Professor.create("pfirst_name" => "David", "plast_name" => "Dranove", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/dranove_david.ashx")
brianuzzi = Professor.create("pfirst_name" => "Brian", "plast_name" => "Uzzi", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/uzzi_brian_2012.ashx")
craiggarthwaite = Professor.create("pfirst_name" => "Craig", "plast_name" => "Garthwaite", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Garthwaite_Craig_2011.ashx")
edwardfxhughes = Professor.create("pfirst_name" => "Edward F.X.", "plast_name" => "Hughes", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Hughes_Edward13_RGB.ashx")
jamesconley = Professor.create("pfirst_name" => "James", "plast_name" => "Conley", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Conley_James_2011.ashx")


Section.delete_all
hema914brown = Section.create("course_id" => hema914.id, "professor_id" => jenbrown.id)
mgmt431gathwaite = Section.create("course_id" => mgmt431.id, "professor_id" => craiggarthwaite.id)
hema914calkins = Section.create("course_id" => hema914.id, "professor_id" => timcalkins.id)


Rating.delete_all
Rating.create("section_id" => hema914brown.id, "rating" => "4", "feedback" => "Great!")
Rating.create("section_id" => mgmt431gathwaite.id, "rating" => "6", "feedback" => "Perfect!")
Rating.create("section_id" => hema914calkins.id, "rating" => "8", "feedback" => "the best!")
Rating.create("section_id" => hema914calkins.id, "rating" => "3", "feedback" => "Awesome!")
